### ISSUE TITLE
Facebook login token format

### ISSUE THREAD

**Issue by Scieon** [Project-Epsilon/server#35]
Facebook login token has hashtag at the end of token.
End of token hashtag seems to prevent logging in

example: Vp9IiGVyrw#_=_

**Comment by ghiobi** [comment]
http://stackoverflow.com/questions/7131909/facebook-callback-appends-to-return-url

Facebook appends #_=_ to the redirect url for security reasons.
The solution to this problem was to append another parameter at the very end of our redirect url so that we isolate the critical data more precisely.

We solution we made in https://github.com/Project-Epsilon/server/pull/34.

👍
